Repository Allie-Knowing/Hecarim, pull requests merged in 2022-04, with the labels that each got.

#50 #27 Modify search feature
  src/assets/icons/Search/Back_btn.png
  src/assets/icons/Search/Reset_text.png
  src/components/SearchPage/SearchResults/DefaultSearchPage/index.tsx
  src/components/SearchPage/SearchResults/DefaultSearchPage/style.ts
  src/components/SearchPage/SearchResults/SearchedQuestionsPage/BackBtn/index.tsx
  src/components/SearchPage/SearchResults/SearchedQuestionsPage/BackBtn/style.ts
  src/components/SearchPage/SearchResults/SearchedQuestionsPage/index.tsx
  src/components/SearchPage/SearchResults/SearchedQuestionsPage/style.ts
  src/components/SearchPage/SearchResults/index.tsx
  src/components/SearchPage/SearchTopNavigation/InputNavigation/index.tsx
  src/components/SearchPage/SearchTopNavigation/InputNavigation/style.ts
  src/components/SearchPage/SearchTopNavigation/TitleNavigation/index.tsx
  src/components/SearchPage/SearchTopNavigation/TitleNavigation/style.ts
  src/components/SearchPage/SearchTopNavigation/index.tsx
  src/components/SearchPage/SearchTopNavigation/style.ts
  src/screens/Search/index.tsx
Labels: Page | 유저/로그인/검색, 기능, 스타일

#53 52 Stack Question List
  App.tsx
  src/components/BottomTabNavigation/index.tsx
  src/components/FeedContent/index.tsx
  src/components/FeedVideos/index.tsx
  src/components/QuestionList/index.tsx
  src/components/QuestionList/styles.ts
  src/components/VideoAnswerContent/index.tsx
  src/context/IsStackContext.ts
  src/hooks/useMainStackNavigation.ts
  src/screens/Feed.tsx
  src/screens/StackedQuestionList.tsx
Labels: 기능

#55 46 카메라 rn/navigation stack으로 구현
  src/components/BottomTabNavigation/index.tsx
  src/components/Question/Camera/index.tsx
  src/components/Question/Camera/styles.ts
  src/components/Question/VideoDetail/index.tsx
  src/components/Question/VideoDetail/styles.ts
  src/components/Question/index.tsx
Labels: Page | 영상제작

#90 #64 Modify 64 branch
  .eslintrc.js
  src/api/Search.ts
  src/components/SearchPage/SearchResults/DefaultSearchPage/index.tsx
  src/components/SearchPage/SearchResults/DefaultSearchPage/style.ts
  src/components/SearchPage/SearchTopNavigation/InputNavigation/InputValueMapping/index.tsx
  src/components/SearchPage/SearchTopNavigation/InputNavigation/InputValueMapping/style.ts
  src/components/SearchPage/SearchTopNavigation/InputNavigation/index.tsx
  src/components/SearchPage/SearchTopNavigation/InputNavigation/style.ts
  src/components/SearchPage/SearchTopNavigation/index.tsx
  src/constant/queryKeys.ts
  src/hooks/useSearchComplete.ts
  src/modules/dto/response/searchResponse.ts
  src/queries/Like.ts
  src/queries/Search.ts
Labels: Page | 유저/로그인/검색, 기능, 스타일

#94 Feature/89 apple oauth
  package.json
  src/api/Signin.ts
  src/assets/profile.png
  src/components/Buttons/Login/AppleButton.tsx
  src/components/Buttons/Login/GoogleButton.tsx
  src/components/Buttons/Login/NaverButton.tsx
  src/components/Buttons/Login/styles.ts
  src/components/MyQuestionList/MyQuestion/index.tsx
  src/components/MyQuestionList/MyQuestion/style.ts
  src/components/MyQuestionList/index.tsx
  src/components/Profile/index.tsx
  src/constance/uri.ts
  src/constant/env.ts
  src/layout/loginButton/styles.ts
  src/queries/Profile.ts
  src/screens/Login/index.tsx
  src/screens/Login/style.ts
  yarn.lock
Labels: 기능

#92 88 Feed API Query
  App.tsx
  src/api/Answer.ts
  src/api/Like.ts
  src/api/Question.ts
  src/api/TextAnswer.ts
  src/api/Video.ts
  src/components/Alert/index.tsx
  src/components/BottomSheets/Comments/index.tsx
  src/components/Buttons/Setting/LogoutButton.tsx
  src/components/Comment/index.tsx
  src/components/FeedContent/index.tsx
  src/components/FeedContent/styles.ts
  src/components/FeedVideos/index.tsx
  src/components/QuestionList/index.tsx
  src/components/VideoAnswer/index.tsx
  src/components/VideoAnswer/styles.ts
  src/components/VideoAnswerContent/index.tsx
  src/components/VideoAnswerContent/styles.ts
  src/constance/uri.ts
  src/constant/queryKeys.ts
  src/hooks/useAlert.ts
  src/hooks/useMainStackNavigation.ts
  src/queries/Answer.ts
  src/queries/Like.ts
  src/queries/Question.ts
  src/queries/TextAnswer.ts
  src/queries/Video.ts
  src/screens/Feed.tsx
  src/screens/StackedQuestionList.tsx
  src/utils/api/answer/index.ts
  src/utils/api/textAnswer/index.ts
  src/utils/axios/index.ts
  src/utils/axios/refresh.ts
  tsconfig.json
Labels: 기능

#97 Feature/95 mypage question video
  src/components/BottomTabNavigation/index.tsx
  src/components/Buttons/Login/GoogleButton.tsx
  src/components/Buttons/Setting/LogoutButton.tsx
  src/components/Header/Login/index.tsx
  src/components/Header/Login/style.ts
  src/screens/Login/index.tsx
  src/screens/MyPage/MyPage.tsx
  src/utils/axios/index.ts
Labels: minor

#93 카메라 연동
  App.tsx
  package.json
  src/assets/icons/back-white.png
  src/components/Question/Camera/index.tsx
  src/components/Question/Camera/styles.ts
  src/components/Question/CameraDetail/index.tsx
  src/components/Question/CameraDetail/styles.ts
  src/components/Question/VideoDetail/index.tsx
  src/components/Question/index.tsx
  src/constance/uri.ts
  src/hooks/useMainStackNavigation.ts
  src/queries/useVideoData.ts
  src/queries/useVideoUrl.ts
  src/utils/api/videoData/index.ts
  src/utils/api/videoUrl/index.ts
  src/utils/hooks/videoData/useVideoData.ts
  src/utils/hooks/videoUrl/useGetVideoUrl.ts
  yarn.lock
Labels: Page | 영상제작

#105 질문 영상 연결
  App.tsx
  src/components/Question/Camera/index.tsx
  src/components/Question/CameraDetail/index.tsx
  src/components/Question/index.tsx
  src/hooks/useMainStackNavigation.ts
  src/utils/saga/createRequestSaga.ts
Labels: Page | 영상제작

#117 영상 답변 생성 안켜지는 버그
  App.tsx
  src/components/FeedContent/index.tsx
  src/components/Question/CameraDetail/index.tsx
  src/hooks/useMainStackNavigation.ts
Labels: Page | 영상제작

#120 auto 해쉬태그 기능
  src/components/Question/Camera/index.tsx
Labels: Page | 영상제작

#123 auto 해쉬태그 기능
  src/components/Question/CameraDetail/index.tsx
Labels: Page | 영상제작

#126 125 Debuging Feed Feature
  App.tsx
  src/components/FeedContent/index.tsx
  src/components/FeedVideos/index.tsx
  src/components/QuestionList/index.tsx
  src/components/VideoAnswerContent/index.tsx
  src/utils/axios/index.ts
Labels: 버그
