Repository Allie-Knowing/Hecarim, pull requests merged in 2022-05, with the labels that each got.

#162 156 fix tier name
  src/components/Wallet/TierModal/TierLine/index.tsx
  src/components/Wallet/TierModal/TierLine/style.ts
  src/components/Wallet/TierModal/index.tsx
  src/components/Wallet/TierModal/style.ts
  src/components/Wallet/WalletInfo/index.tsx
  src/components/Wallet/WalletInfo/style.ts
Labels: 스타일

#164 146 fix stack question list bug
  src/components/FeedVideos/index.tsx
  src/components/MyQuestionList/index.tsx
  src/components/QuestionList/index.tsx
  src/components/SearchPage/SearchResults/SearchedQuestions/Results/index.tsx
  src/components/SearchPage/SearchResults/SearchedQuestions/index.tsx
Labels: 기능

#167 155 feed views api
  src/api/Views.ts
  src/components/FeedContent/index.tsx
  src/components/VideoAnswerContent/index.tsx
  src/constance/uri.ts
  src/queries/Views.ts
Labels: 기능

#166 165 fix ios app tracking conflict
  App.tsx
  src/hooks/useNotificationPermission.ts
  src/screens/Feed.tsx
Labels: 버그

#169 #149 Fix refresh bug
  src/api/Signin.ts
  src/constant/expiresTime.ts
  src/constant/storageKeys.ts
  src/utils/axios/index.ts
Labels: 버그

#175 Add video answer count on nav label
  App.tsx
  package.json
  src/api/Answer.ts
  src/atom/videoAnswerCount.ts
  src/components/QuestionList/index.tsx
  src/components/VideoAnswer/index.tsx
  src/constance/uri.ts
  src/constant/atomKeys.ts
  src/constant/queryKeys.ts
  src/queries/Answer.ts
  yarn.lock
Labels: 기능

#174 3초 이하 영상 임포트 막기
  src/components/Question/Camera/index.tsx
  src/constant/camera.ts
Labels: 버그

#179 #135 Fix count bug
  src/api/Answer.ts
  src/atom/videoAnswerCount.ts
  src/components/VideoAnswer/index.tsx
Labels: 버그

#177 141 add userpage my answer
  .gitignore
  App.tsx
  package.json
  src/api/MyId.ts
  src/api/Profile.ts
  src/components/MyQuestionList/Switch/index.tsx
  src/components/MyQuestionList/Switch/style.ts
  src/components/MyQuestionList/index.tsx
  src/components/MyQuestionList/style.ts
  src/components/Profile/index.tsx
  src/constance/uri.ts
  src/constant/queryKeys.ts
  src/queries/Profile.ts
  src/screens/Feed.tsx
  src/screens/MyPage/MyPage.tsx
  src/screens/MyPage/UserPage.tsx
  src/screens/StackedQuestionList.tsx
  src/utils/api/notification/index.ts
Labels: 기능

#186 148 Push To User Profile On Press Comment Profile Img
  App.tsx
  src/components/BottomSheets/Comments/index.tsx
  src/components/Comment/index.tsx
  src/components/FeedContent/index.tsx
Labels: 기능

#190 183 Implement User Follow Feature
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/screens/MyPage/MyPage.tsx
  src/screens/MyPage/UserPage.tsx
Labels: 기능
